const SYMBOLS = {
    "...": "ellipses",
    ":=>": "penis",
    "~=": "neq",
    "==": "eq",
    ">=": "geq",
    "<=": "leq",
    "=>": "arrow",
    "..": "str_concat",
    "&&": "and",
    "||": "or",
    ">>": "zoom",
    "<<": "lshift",
    "//": "floor_div",
    "**": "exponent",
    "^": "up",
    "+": "plus",
    "-": "minus",
    "*": "times",
    "/": "divide",
    "=": "equals",
    "!": "excl",
    ".": "dot",
    ":": "colon",
    ",": "comma",
    "<": "lt",
    ">": "gt",
    "#": "pound",
    "[": "open_square",
    "]": "close_square",
    "(": "open_paren",
    ")": "close_paren",
    "{": "open_curly",
    "}": "close_curly",
    ";": "semicolon",
    "?": "question_mark",
    "|": "union",
    "@": "at",
    "%": "percent"
};

exports.SYMBOLS = SYMBOLS;
